### ISSUE TITLE
[맛집 상세보기] 맛집 상세보기 기능 구현

### ISSUE THREAD

**Issue by BENDENG1** [boostcampwm2023/and06-nibobnebob#104]
### Description

사용자는 음식점에 대한 상세 정보를 확인할 수 있어야 한다.

---

### Task

사용자는 각 리뷰에 포함된 사진과 정보를 볼 수 있어야 한다.
사용자는 내 위시 맛집 리스트에 음식점을 추가하거나 삭제할 수 있는 버튼이 있어야 한다.
사용자는 맛집리스트 추가/삭제 버튼을 클릭하여 음식점을 나의 리스트에 추가하거나 삭제할 수 있어야 한다.
사용자는 해당 리뷰에 대한 평가를 남길 수 있어야 한다.
사용자는 각각의 리뷰를 클릭할 때 리뷰 상세 보기 페이지로 이동할 수 있어야 한다.

#### AOS
- [x] 음식점에 대한 이름,위치,영업시간,메뉴,가격을 보여준다.
- [x] 공통질문에 대한 리뷰와 평가를 함께 리스트로 표시한다.
- [x] 요청한 위시맛집리스트 추가에 대해서 추가되었음을 표시한다.
- [x] 요청한 맛집리스트 추가에 대해서 추가/삭제가 되었음을 표시한다.
- [x] 각 리뷰에 대한 좋아요/싫어요 평가를 표시한다.
- [x] 각 리뷰에 대한 평가 후 평가완료에 대해 표시해준다.
- [x] 사용자의 리뷰 클릭 시 해당 사용자의 상세리뷰페이지로 이동한다.

#### BE
- [x] 음식점에 대한 상세정보를 요청 해 서버에서 응답한다.
- [x] 각 리뷰에 대한 정보를 요청을 서버에서 응답한다.
- [x] 위시맛집리스트 버튼 추가 시 위시 맛집리스트 추가를 요청하고 서버에서 응답한다.
- [x] 맛집리스트 버튼 추가 시 맛집리스트 추가를 요청하고 서버에서 응답한다.
- [x] 각 리뷰에 대한 평가 진행 후 서버에 반영하며 응답한다.

---

### Acceptance Criteria

- [x]  사용자는 음식점 페이지에서 위치, 영업 시간, 메뉴, 가격 등의 정보를 볼 수 있다.
- [x] 정보 페이지는 사용자에게 충분한 상세 정보를 제공해야 한다.
- [x] 사용자는 리뷰 섹션에서 다른 사용자들이 올린 사진과 리뷰를 볼 수 있다.
- [x] 각 리뷰에는 평점, 방문 날짜, 사용자의 의견이 포함되어야 한다.
- [x] 사용자는 음식점 정보 페이지에 위시 리스트 추가/삭제 버튼을 볼 수 있다.
- [x] 추가/삭제 버튼을 클릭하면, 해당 음식점이 사용자의 위시 리스트에 즉시 반영된다.
- [x] 맛집 정보 페이지에는 사용자가 맛집을 자신의 리스트에 추가하거나 삭제할 수 있는 버튼이 있다.
- [x] 해당 버튼을 사용하여 맛집 리스트의 항목을 추가하거나 제거할 수 있다.
- [x] 사용자는 맛집 상세 페이지에서 리뷰에 대한 평가를 남길 수 있는 옵션을 볼 수 있다.
- [x] 평가 옵션에는 좋아요, 싫어요 버튼 또는 별점 주기 등이 포함될 수 있다.
- [x] 사용자가 평가를 완료하면, 그 평가는 실시간으로 리뷰에 반영되어 다른 사용자들에게 표시된다.
- [x] 각 리뷰는 클릭 가능하며, 클릭 시 상세 리뷰 페이지로 이동한다.
- [x] 상세 페이지에는 리뷰 전문, 사용자의 추가 사진, 상세 평점 등이 표시된다.

---
