### ISSUE TITLE
[Setting] aos 초기 세팅 

### ISSUE THREAD

**Issue by plashdof** [boostcampwm2023/and06-nibobnebob#4]
### Description

---

### Task

- [x]  프로젝트 생성
- [x]  사용 drawable icon 추가
- [x]  gradle dependency 추가
- [x]  패키지 구조화 (Readme 에 정리)

---
