### ISSUE TITLE
[Home-Final] 사용자 메뉴 추천 기능

### ISSUE THREAD

**Issue by GeunH** [boostcampwm2023/and06-nibobnebob#64]
### Description

사용자는 메뉴 추천에 버튼 클릭 시 메뉴 추천을 받을 수 있어야한다.

---

### Task

선택시 음식에 맞게 화면에 띄워준다
다시 돌리기 버튼 클릭 시 음식에 대한 추천을 다시 진행한다
취소버튼 클릭시 모달창이 사라지게 된다.

#### AOS
- [ ] 선택시 음식에 맞게 화면에 띄워준다
- [ ] 다시 돌리기 버튼 클릭 시 음식에 대한 추천을 다시 진행한다
- [ ] 취소버튼 클릭시 모달창이 사라지게 된다.

#### BE
- [ ]  메뉴 추천버튼 클릭 시 추천할 음식을 요청해 서버에서 응답한다.

---

### Acceptance Criteria

- [ ] 메뉴 추천 버튼이 존재하며 클릭 시 사용자에게 메뉴 추천을 제공한다.
- [ ] 추천 받은 메뉴는 '선택', '다시 돌리기', '취소'의 옵션을 가진다.

---
