### ISSUE TITLE
[Setting] BE 초기 세팅

### ISSUE THREAD

**Issue by GeunH** [boostcampwm2023/and06-nibobnebob#8]
### Description
BE 초기 세팅
---

### Task
- [x]  nest.js 설치
- [x]  eslint, prettier 적용
- [x]  nest swagger 설치

---
